In [2]:
import requests
import pandas as pd
import numpy as np
import sqlalchemy

In [2]:
import requests

headers = {
    'authority': 'api2.realtor.ca',
    'accept': '*/*',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'sec-gpc': '1',
    'origin': 'https://www.realtor.ca',
    'sec-fetch-site': 'same-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.realtor.ca/',
    'accept-language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'cookie': 'visid_incap_2269415=ViIClk1ZRqOgAtVFuM4NDpcqKWIAAAAAQUIPAAAAAADjUiJ0t2YvMVRS7LhTMiJB; nlbi_2269415=CIy0U2vGaAODLC+okG5lugAAAACUDggb9G3pX6HXI2IGGLsl; gig_bootstrap_3_mrQiIl6ov44s2X3j6NGWVZ9SDDtplqV7WgdcyEpGYnYxl7ygDWPQHqQqtpSiUfko=gigya-pr_ver4; incap_ses_489_2269415=4HvZJ+lVXA9i+Z0RjkfJBuU7KmIAAAAA/1RoPjfpmoPNVvBN6DqD7Q==; ASP.NET_SessionId=a5ohnf5vyvfd0vf2d54hzk5x; visid_incap_2271082=QGMM5iQ3Ra69iRvB8bW1Ouw7KmIAAAAAQUIPAAAAAACJOKzmVesbIamg+eoUn2o9; nlbi_2271082=7FTvQo68Vnlnf2+VcbDG1QAAAABMmBALQCVqozNcvZvT0aY4; incap_ses_505_2269415=pqfIdzFWYR8JUDO9cx8CB+myKmIAAAAA4PlxDDHY5BkM2/DXliOuWA==; incap_ses_1445_2269415=ZaelC68tP259WWulDawNFIC1KmIAAAAAPjnvXlYsFwBITjP6kqfPEQ==; incap_ses_505_2271082=NHtcMukFwh9qWDS9cx8CB4S1KmIAAAAAtUnpZNR+5IqNLZ5Jh267WQ==; reese84=3:mrhQe17QplYhLpX6NQlC3w==:4pBfHkszokO4j2byOYWHfWJi3x/ZwPySkqX4yw+SVQ1u9LOdk/b8AkmbaVxF5lUZxNUZUxrREU9pobDAF8a1Khnafu7GIpl+/iapRitUm1mQVGnQQVLMqv5DJch0EYgJZYlL7XTKbd0w+cEcZ8wSCkxuxsUQNVFvr97RUDHw2thikgIMcTi4kwkPHpMCNw3YzNaOM9p4OHz25An2FPeLMTbW23p4jUrs7rqbv1PPIQY306HzKwcM6eEYDzoDdeA/Wfl5rCiPOs1+2myUcLGELJnLzBSfIb+n2bfMXSjerYAP0o34pX19q5SBftlxvSWhQPGhe73+E7w5YhiMNdiFyCBf5/lTp+ks0mCnRyMcM9R8VKdprPC/clyG0RxR+A1oIY3gwv05Tk4Mw6VssB7NCsEfn6wW8pPw5iXI2CzRA0FymW9ItFyCXOo7z3fB1phX:/7Uk6TU/9r5L6JVF96qBWTxs1QtpPGMISXAbWQVXXFk=; nlbi_2269415_2147483392=0/NDb32hnncXlk00kG5lugAAAABtBzIVa4rtJs/er3jtjd+N',
}

data = {
  'ZoomLevel': '9',
  'LatitudeMax': '44.76542',
  'LongitudeMax': '-77.38739',
  'LatitudeMin': '43.05601',
  'LongitudeMin': '-81.74347',
  'Sort': '1-A',
  'PropertyTypeGroupID': '1',
  'PropertySearchTypeId': '1',
  'TransactionTypeId': '3',
  'Currency': 'CAD',
  'RecordsPerPage': '12',
  'ApplicationId': '1',
  'CultureId': '1',
  'Version': '7.0',
  'CurrentPage': '3'
}

response = requests.post('https://api2.realtor.ca/Listing.svc/PropertySearch_Post', headers=headers, data=data)

In [3]:
response

In [4]:
result_json = response.json()

In [5]:
result_json.keys()

dict_keys(['ErrorCode', 'Paging', 'Results', 'Pins', 'GroupingLevel'])

In [6]:
len(result_json['Results'])

12

In [7]:
result_items = result_json['Results']

In [11]:
result_items[0]

{'Id': '24106499',
 'MlsNumber': 'C5524409',
 'PublicRemarks': 'Welcome To Yonge+Rich | One Locker Available For Rent | Must Be A Current Resident | Pls Provide Proof Of Residency (29630908)',
 'Building': {'BathroomTotal': '0',
  'StoriesTotal': '',
  'Type': 'Other',
  'Ammenities': 'Storage - Locker'},
 'Individual': [{'IndividualID': 1991122,
   'Name': 'JOEY WONG',
   'Organization': {'OrganizationID': 288527,
    'Name': 'SKYLETTE MARKETING REALTY INC.',
    'Address': {'AddressText': '50 ACADIA AVE #122|MARKHAM, Ontario L3R0B3',
     'PermitShowAddress': True,
     'DisseminationArea': None},
    'Phones': [{'PhoneType': 'Telephone',
      'PhoneNumber': '269-7733',
      'AreaCode': '416',
      'PhoneTypeId': '1'},
     {'PhoneType': 'Fax',
      'PhoneNumber': '475-4770',
      'AreaCode': '905',
      'PhoneTypeId': '4'}],
    'Emails': [{'ContactId': '463342221'}],
    'OrganizationType': 'Firm',
    'Designation': 'Brokerage',
    'HasEmail': True,
    'PermitFreetextEmail': True,
    'PermitShowListingLink': True,
    'RelativeDetailsURL': '/office/firm/288527/skylette-marketing-realty-inc-50-acadia-ave-122-markham-ontario-l3r0b3',
    'PhotoLastupdate': '2022-03-04 7:28:47 PM'},
   'Phones': [{'PhoneType': 'Telephone',
     'PhoneNumber': '617-3030',
     'AreaCode': '416',
     'PhoneTypeId': '1'}],
   'Emails': [{'ContactId': '463342585'}],
   'Photo': 'https://cdn.realtor.ca/individual/TS0/lowres/1991122.jpg',
   'Position': 'Broker of Record',
   'PermitFreetextEmail': True,
   'FirstName': 'JOEY',
   'LastName': 'WONG',
   'CorporationDisplayTypeId': '0',
   'PermitShowListingLink': True,
   'RelativeDetailsURL': '/agent/1991122/joey-wong-50-acadia-ave-122-markham-ontario-l3r0b3',
   'PhotoHighRes': 'https://cdn.realtor.ca/individual/TS0/highres/1991122.jpg',
   'RankMyAgentKey': '',
   'RealSatisfiedKey': ''}],
 'Property': {'LeaseRent': '$100/Monthly',
  'Type': 'Single Family',
  'Address': {'AddressText': '20 LOMBARD ST|Toronto, Ontario M5C0A6',
   'Longitude': '-79.3769244',
   'Latitude': '43.6516473',
   'PermitShowAddress': True,
   'DisseminationArea': None},
  'Photo': [{'SequenceId': '1',
    'HighResPath': 'https://cdn.realtor.ca/listings/TS637820800277200000/reb82/highres/9/c5524409_1.jpg',
    'MedResPath': 'https://cdn.realtor.ca/listings/TS637820800277200000/reb82/medres/9/c5524409_1.jpg',
    'LowResPath': 'https://cdn.realtor.ca/listings/TS637820800277200000/reb82/lowres/9/c5524409_1.jpg',
    'LastUpdated': '2022-03-05 12:27:07 PM'}],
  'TypeId': '300',
  'OwnershipType': 'Condominium/Strata',
  'ConvertedPrice': ' $100/Monthly',
  'OwnershipTypeGroupIds': [2],
  'LeaseRentUnformattedValue': '100'},
 'Business': {},
 'Land': {'SizeTotal': '.'},
 'PostalCode': 'M5C0A6',
 'RelativeDetailsURL': '/real-estate/24106499/20-lombard-st-toronto-church-yonge-corridor',
 'StatusId': '1',
 'PhotoChangeDateUTC': '2022-03-05 5:27:07 PM',
 'Distance': '',
 'RelativeURLEn': '/real-estate/24106499/20-lombard-st-toronto-church-yonge-corridor',
 'RelativeURLFr': '/immobilier/24106499/20-lombard-st-toronto',
 'Media': [],
 'InsertedDateUTC': '637820369273500000',
 'TimeOnRealtor': '7 days ago'}

In [12]:
result_items[0]["Building"]["BathroomTotal"]

'0'

In [13]:
result_items[0]['PublicRemarks']

'Welcome To Yonge+Rich | One Locker Available For Rent | Must Be A Current Resident | Pls Provide Proof Of Residency (29630908)'

In [14]:
result_items[0]['Property']['Address']['AddressText']

'20 LOMBARD ST|Toronto, Ontario M5C0A6'

In [15]:
result_items[0]['Building']['Bedrooms']

KeyError: 'Bedrooms'

In [16]:
result_items[0]['Individual'][0]['Phones'][0]['AreaCode']

'416'

In [17]:
result_items[0]['Property']['LeaseRent']

'$100/Monthly'

In [18]:
result_items[0]['Property']['ParkingSpaceTotal']

KeyError: 'ParkingSpaceTotal'

In [19]:
result_items[0]['Property']['Type']

'Single Family'

In [21]:
result_items[0]['Property']['Address']['Latitude']

'43.6516473'

# Get All Pages

In [27]:
import requests

address= []
bedrooms= []
bathrooms = []
areacode= []
price= []
parking_space= []
property_type= []
public_remarks = []

for i in range(1,51):
    import requests
    headers = {
        'authority': 'api2.realtor.ca',
        'accept': '*/*',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'sec-gpc': '1',
        'origin': 'https://www.realtor.ca',
        'sec-fetch-site': 'same-site',
        'sec-fetch-mode': 'cors',
        'sec-fetch-dest': 'empty',
        'referer': 'https://www.realtor.ca/',
        'accept-language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
        'cookie': 'visid_incap_2269415=ViIClk1ZRqOgAtVFuM4NDpcqKWIAAAAAQUIPAAAAAADjUiJ0t2YvMVRS7LhTMiJB; nlbi_2269415=CIy0U2vGaAODLC+okG5lugAAAACUDggb9G3pX6HXI2IGGLsl; gig_bootstrap_3_mrQiIl6ov44s2X3j6NGWVZ9SDDtplqV7WgdcyEpGYnYxl7ygDWPQHqQqtpSiUfko=gigya-pr_ver4; incap_ses_489_2269415=4HvZJ+lVXA9i+Z0RjkfJBuU7KmIAAAAA/1RoPjfpmoPNVvBN6DqD7Q==; ASP.NET_SessionId=a5ohnf5vyvfd0vf2d54hzk5x; visid_incap_2271082=QGMM5iQ3Ra69iRvB8bW1Ouw7KmIAAAAAQUIPAAAAAACJOKzmVesbIamg+eoUn2o9; nlbi_2271082=7FTvQo68Vnlnf2+VcbDG1QAAAABMmBALQCVqozNcvZvT0aY4; incap_ses_505_2269415=pqfIdzFWYR8JUDO9cx8CB+myKmIAAAAA4PlxDDHY5BkM2/DXliOuWA==; incap_ses_1445_2269415=ZaelC68tP259WWulDawNFIC1KmIAAAAAPjnvXlYsFwBITjP6kqfPEQ==; incap_ses_505_2271082=NHtcMukFwh9qWDS9cx8CB4S1KmIAAAAAtUnpZNR+5IqNLZ5Jh267WQ==; reese84=3:mrhQe17QplYhLpX6NQlC3w==:4pBfHkszokO4j2byOYWHfWJi3x/ZwPySkqX4yw+SVQ1u9LOdk/b8AkmbaVxF5lUZxNUZUxrREU9pobDAF8a1Khnafu7GIpl+/iapRitUm1mQVGnQQVLMqv5DJch0EYgJZYlL7XTKbd0w+cEcZ8wSCkxuxsUQNVFvr97RUDHw2thikgIMcTi4kwkPHpMCNw3YzNaOM9p4OHz25An2FPeLMTbW23p4jUrs7rqbv1PPIQY306HzKwcM6eEYDzoDdeA/Wfl5rCiPOs1+2myUcLGELJnLzBSfIb+n2bfMXSjerYAP0o34pX19q5SBftlxvSWhQPGhe73+E7w5YhiMNdiFyCBf5/lTp+ks0mCnRyMcM9R8VKdprPC/clyG0RxR+A1oIY3gwv05Tk4Mw6VssB7NCsEfn6wW8pPw5iXI2CzRA0FymW9ItFyCXOo7z3fB1phX:/7Uk6TU/9r5L6JVF96qBWTxs1QtpPGMISXAbWQVXXFk=; nlbi_2269415_2147483392=0/NDb32hnncXlk00kG5lugAAAABtBzIVa4rtJs/er3jtjd+N',
    }

    data = {
      'ZoomLevel': '9',
      'LatitudeMax': '44.76542',
      'LongitudeMax': '-77.38739',
      'LatitudeMin': '43.05601',
      'LongitudeMin': '-81.74347',
      'Sort': '1-A',
      'PropertyTypeGroupID': '1',
      'PropertySearchTypeId': '1',
      'TransactionTypeId': '3',
      'Currency': 'CAD',
      'RecordsPerPage': '12',
      'ApplicationId': '1',
      'CultureId': '1',
      'Version': '7.0',
      'CurrentPage': i
    }

    response = requests.post('https://api2.realtor.ca/Listing.svc/PropertySearch_Post', headers=headers, data=data)
    response = requests.post('https://api2.realtor.ca/Listing.svc/PropertySearch_Post', headers=headers, data=data)
    result_json = response.json()
    result_items = result_json['Results']
    
    for result in result_items:
        try:
            address.append(result['Property']['Address']['AddressText'])
        except:
            address.append(np.nan)

        try:
            bedrooms.append(result['Building']['Bedrooms'])
        except:
            bedrooms.append(np.nan)

        try:
            bathrooms.append(result['Building']['BathroomTotal'])
        except:
            bathrooms.append(np.nan)
            
        try:
            public_remarks.append(result['PublicRemarks'])
        except:
            public_remarks.append(np.nan)

        try:
            areacode.append(result['Individual'][0]['Phones'][0]['AreaCode'])
        except:
            areacode.append(np.nan)


        try:
            price.append(result['Property']['LeaseRent'])
        except:
            price.append(np.nan)


        try:
            parking_space.append(result['Property']['ParkingSpaceTotal'])
        except:
            parking_space.append(np.nan)


        try:
            property_type.append(result['Property']['Type'])
        except:
            property_type.append(np.nan)

In [34]:
df_gta = pd.DataFrame({'Address': address,
                            'bedrooms':bedrooms,
                            'bathrooms': bathrooms,
                            'public_remarks':public_remarks,
                            'areacode': areacode,
                            'price': price,
                            'parking_space': parking_space,
                            'property_type':property_type,
                          })

In [35]:
df_gta

,Address,bedrooms,bathrooms,public_remarks,areacode,price,parking_space,property_type
0,"800 SALEM RD N|Ajax, Ontario L1Z0B1",NaN,NaN,Rare Land Lease Opportunity On The South/East ...,905,$1/Monthly,NaN,Vacant Land
1,"116 AVENUE RD|Toronto, Ontario M5R2H4",NaN,NaN,Tremendous Short-Term Land Lease Opportunity W...,416,$1/Monthly,NaN,Vacant Land
2,"#6 -0 BELL BLVD|Belleville, Ontario",NaN,NaN,State Of The Art Design Build New Construction...,905,$1/square feet,NaN,Vacant Land
3,"0 PTLT9 CON6 5TH LN SW|Melancthon, Ontario L9V2C0",NaN,NaN,10 Acres Vacant Land For Lease In Melancthon. ...,647,$1/Monthly,NaN,Vacant Land
4,"3457 DORAL DR|Innisfil, Ontario L9S0G1",NaN,NaN,2 Acre Un-Serviced Industrial Lot In The Heart...,416,$1/Monthly,NaN,Vacant Land
...,...,...,...,...,...,...,...,...
595,"#514 -170 BAYVIEW AVE|Toronto, Ontario M5A0G1",0,1,Contemporary Open Concept Bachelor Suite W/ Lo...,905,"$1,550/Monthly",NaN,Single Family
596,"#LOWER -54 CARTER DR|Brampton, Ontario L6V3N5",1,1,"Welcome To A Bright, Freshly Painted, Lower Le...",905,"$1,550/Monthly",NaN,Single Family
597,"48 COLLINGWOOD AVE|Brampton, Ontario L7A1L6",2,1,Legal Bsmt 2 Bedroom Apartment For Rent. Newer...,905,"$1,550/Monthly",1,Single Family
598,"1583 RAMSHAW CRES|Milton, Ontario L9T5L9",2,1,Absolutely Stunning And Welcoming Furnished Ba...,647,"$1,550/Monthly",3,Single Family
599,"220 RAVENSCROFT RD|Ajax, Ontario L1T2T3",2,1,2 Bedroom Basement Apartment In Hear Of Ajax. ...,416,"$1,550/Monthly",NaN,Single Family

In [36]:
df_gta['property_type'].value_counts()

Single Family    579
Vacant Land       21
Name: property_type, dtype: int64

In [37]:
#Everything is Monthly Rent
len(df_gta['price'].str.contains('Monthly'))

600

In [39]:
df_gta.to_excel('GTA_info.xlsx', index=False)

# data after room type labeling

In [3]:
data = pd.read_csv('./GTA_info.csv')

In [4]:
data

,Address,bedrooms,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type
0,"689 DOON VILLAGE Road Unit# 304-3|Kitchener, O...",4 + 0,2,STUDENT BEDROOM RENTAL in MALE-ONLY UNIT. $495...,bedroom,416,$495/Monthly,NaN,Single Family
1,"#1109 -2910 HIGHWAY 7 RD|Vaughan, Ontario L4K0H8",1,1,Solarium Room For Rent* Solarium Has A Window ...,bedroom,905,$700/Monthly,NaN,Single Family
2,"##3 -105 BROCK ST S|Whitby, Ontario L1N4J9",1,1,Fabulous Upper Floor 1 Bedroom Is Available Fo...,bedroom,905,$750/Monthly,NaN,Single Family
3,"#BASEMEN -373 ARROWSMITH DR S|Mississauga, On...",1,1,Location! Location! One Spacious Bedroom Avail...,bedroom,416,$750/Monthly,4.0,Single Family
4,"#UPPER -31B SOUTH STATION ST|Toronto, Ontario ...",1,1,Located Close To Go Station At Weston And Lawr...,upper-unit,905,$750/Monthly,1.0,Single Family
...,...,...,...,...,...,...,...,...,...
550,"#514 -170 BAYVIEW AVE|Toronto, Ontario M5A0G1",0,1,Contemporary Open Concept Bachelor Suite W/ Lo...,apartment,905,"$1,550/Monthly",NaN,Single Family
551,"#LOWER -54 CARTER DR|Brampton, Ontario L6V3N5",1,1,"Welcome To A Bright, Freshly Painted, Lower Le...",basement,905,"$1,550/Monthly",NaN,Single Family
552,"48 COLLINGWOOD AVE|Brampton, Ontario L7A1L6",2,1,Legal Bsmt 2 Bedroom Apartment For Rent. Newer...,basement,905,"$1,550/Monthly",1.0,Single Family
553,"1583 RAMSHAW CRES|Milton, Ontario L9T5L9",2,1,Absolutely Stunning And Welcoming Furnished Ba...,basement,647,"$1,550/Monthly",3.0,Single Family
554,"220 RAVENSCROFT RD|Ajax, Ontario L1T2T3",2,1,2 Bedroom Basement Apartment In Hear Of Ajax. ...,basement,416,"$1,550/Monthly",NaN,Single Family

# separate bedrooms(2+1) into bed(2) and spare room(1)

In [7]:
data['bedroom'] = data['bedrooms'].apply(lambda x: x[0])

In [8]:
data['bedroom'].value_counts()

1    355
2    129
0     63
3      5
4      3
Name: bedroom, dtype: int64

In [9]:
data['spareroom'] = data['bedrooms'].apply(lambda x: x.partition('+')[2] if len(x)> 2 else 0)

In [10]:
data['spareroom'].value_counts()

0     469
 1     42
 0     42
 2      2
Name: spareroom, dtype: int64

In [11]:
data.drop('bedrooms', axis= 1, inplace=True)

# Data Check (check data with unreasonable number)

In [12]:
data[data['bedroom'] == '3']['public_remarks'].ravel()

array(['Welcome to 6 Queen Street! This apartment unit provides 3 spacious bedrooms and a kitchen. Located in Hespeler and surrounded be all the amenities! Steps away from restaurants, shopping and the 401. The unit also includes a large 4 piece bathroom. Each bedroom has good size windows! Be sure to book your showing today! (64341267)',
       'Location, Location! Beautiful Family Neighbourhood! 1 Bedroom Basement Apartment, Main Door Entrance! The Landlord Is Looking For A Small Family Or A Single Individual.**** EXTRAS **** Fridge, Stove, Shared Washer, Shared Dryer. (29564815)',
       'All Inclusive 3 Bedroom And 1 Bathroom Basement With A Spacious Living/ Dining Room In A Quite Neighborhood In Markham. Great Space For A Couple/ Professionals! Walking Distance To Ttc/ Yrt, Pacific Mall, Go Train/Parks, Shopping, Groceries, Restaurants, Parks & More.**** EXTRAS **** Includes Fridge, Stove, Shared Washer, Hydro, Water, Heat, A/C, Internet, Cable Tv, 2 Car Parking (Tandem) (29168102)',
       'All Of The Amenities Just Minutes Away. 5 Minutes Walk To Go Train , Close To The 404 And Shopping Centers, Boundary Of Bayview Secondary High School. Rental Unit Is The Basement Only And Tenant Pays 40% Of Utilities**** EXTRAS **** Extras:Stove, Shared Washer& Dryer, Fridge (29554740)',
       'New Renovated Bright & Spacious Two Bedroom Apartment In The Basement Level Of A Detached House Which Backs Onto Winbourne Park!Quiet Street. Separate Entrance. High Ceiling. All Rooms Have Above Grade Windows. New Laminate Floor, Separate Laundry, One Parking Spot. **Tenant Only Pays 30% Of The Utilities**.Close To Go Train, Bus Stops, Yonge St, 404 And All Your Shopping Needs.**** EXTRAS **** No Access To Garage & Backyard. **Price Is For 2 Bedroom Apt Only**.Stainless Steel Fridge & Stove, Washer & Dryer. Well Maintained Apartment. Must See! (29439472)'],
      dtype=object)

In [13]:
data[data['bedroom'] == '4']['public_remarks'].ravel()

array(['STUDENT BEDROOM RENTAL in MALE-ONLY UNIT. $495/month. Available February 2, 2022. UTILITIES, LAUNDRY, AND INTERNET INCLUDED, SHARED KITCHEN, 2 SHARED BATHROOMS AND LIVING SPACE. 1 bedroom available in a 4 bedroom unit in prime location, minutes to Conestoga College, Hwy 401, groceries, parks, museum, and much more! This modern, newer unit features stainless steel appliances, dishwasher, full-sized in-suite washer and dryer, air exchanger, and carpet-free flooring throughout. NO PARKING. Application Requirements: 1) OREA Rental Application 2) Guarantor 3) Proof of I.D. 4) Proof of Full-time Enrolment. (64188686)',
       'Bedroom For Lease In A New Home In Popular North Area. Price Is $850, All Inclusive. Female Tenant Preferred. Tenant  Will Share The 3 Pc Bath, 2nd Floor Laundry, Kitchen & Common Areas (Which Will Be Furnished). Parking Spot Available For Each Tenant. Utilities Included.**** EXTRAS **** Located Close To Schools, Parks, 407, Shopping. Suitable For Professional, Mature Individual. (29433351)',
       'Luxury, Bright And Spacious With Lots Of Windows. Renovated New Master Bedroom Appox.400 Sq Ft With Brand New 4-Pc Bath, Huge Walk In Closet With Shelves. Shared Kitchen Laundry. Walking Distance To Shops, Groceries, Tim Hortons, Trails, Parks, Markville Mall. Best Schools, Transportations. Car Parking Available, Utilities Included.**** EXTRAS **** Existing Shared Fridge, Stove, Dishwasher, Microwave, Washer & Dryer, Existing Light Fixture & Window Blinds. Cable Tv And Phone Excluded. (29543162)'],
      dtype=object)

In [133]:
data.iloc[0,8] = 0

In [153]:
data.iloc[17, 8] = 1

In [154]:
data.iloc[17, :]['bedroom']

1

In [232]:
data[(data['room type'] == 'bedroom') & (data['spareroom'] >=1)]

,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
13,2,"All Upper Level 3 Br For Lease , Shared Kitche...",bedroom,647,800,2.0,Single Family,1,1,Toronto,Ontario M1B1R6,#ROOM -44 APPLEMORE RD

In [236]:
data[(data['room type'] == 'bedroom') & (data['spareroom'] >=1)]['public_remarks'].ravel()

array(['All Upper Level 3 Br For Lease , Shared Kitchen And Common Area With Landlord . You Can Rent 1 , 2 , 3 Rooms Flexibly. .... Lovely 5 Level Backsplit At Markham/Nugget. 3 Spacious Bedrooms, Formal Dining Room Overlooks Living Room With Walk-Out To Huge Deck In Backyard. Lower Level Family Room With Fireplace & Wet Bar. Newer Roof Shingles, Windows, Furnace & Air Cond. Steps To Ttc, Mosque,**** EXTRAS **** Tenant And Agent Verify All Info Please (29499408)'],
      dtype=object)

In [237]:
data.iloc[13, 8] = 0

In [241]:
data.iloc[13, :]

bathrooms                                                         2
public_remarks    All Upper Level 3 Br For Lease , Shared Kitche...
room type                                                   bedroom
areacode                                                        647
price                                                           800
parking_space                                                     2
property_type                                         Single Family
bedroom                                                           1
spareroom                                                         0
city                                                        Toronto
province                                             Ontario M1B1R6
address                                      #ROOM -44 APPLEMORE RD
Name: 13, dtype: object

In [43]:
data[data['city'] =='Durham']['public_remarks'].ravel()

array(['2 bedroom, 1 bathroom apartment located in a converted church in the quaint town of Durham with a well-equipped kitchen and just steps from downtown. Lovely community with plenty of beautiful scenery to enjoy including a large public park across the street, the Saugeen River, McGowan Falls, and picturesque trails. Parking includes 2 exclusive spaces and additional visitor parking. Covid 19 protocols in place. (64123198)'],
      dtype=object)

In [44]:
data[data['city'] =='Durham']

,Unnamed: 0,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
381,467,1,"2 bedroom, 1 bathroom apartment located in a c...",apartment,647,1500,8.0,Single Family,2,0,Durham,Ontario N0G1R0,108 QUEEN Street N

In [39]:
data[(data['city'] =='Markham') & (data['room type']== 'bedroom')]

,Unnamed: 0,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
7,8,2,Fully Furnished 1 Bedroom For Rent. Well Maint...,bedroom,416,800,1.0,Single Family,1,0,Markham,Ontario L6B0J3,#(1BR) -11 SUMMERSIDE ST

In [40]:
data[(data['city'] =='Markham') & (data['bedroom']>=4)]

,Unnamed: 0,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
85,97,1,"Luxury, Bright And Spacious With Lots Of Windo...",apartment,416,1200,2.0,Single Family,4,0,Markham,Ontario L3S1G5,19 DEVONSHIRE AVE

In [52]:
data[data['parking_space']>=2]['public_remarks'].ravel()

array(['Location! Location! One Spacious Bedroom Available, Partly Furnished In Shared Accommodation In 2 Bedroom Basement. Separate Entrance In Maedowvale Village. Shared Open Concept  Kitchen, Living And Dining Room. Shared Laundry On Main Floor. Located Near Grocery Stores, Heartland.**** EXTRAS **** Available: Fridge, Stove, Microwave. Rental Amount Includes Utilities (Heat, Water, Hydro Only) Please Follow Covid Protocols. (29498717)',
       'All Upper Level 3 Br For Lease , Shared Kitchen And Common Area With Landlord . You Can Rent 1 , 2 , 3 Rooms Flexibly. .... Lovely 5 Level Backsplit At Markham/Nugget. 3 Spacious Bedrooms, Formal Dining Room Overlooks Living Room With Walk-Out To Huge Deck In Backyard. Lower Level Family Room With Fireplace & Wet Bar. Newer Roof Shingles, Windows, Furnace & Air Cond. Steps To Ttc, Mosque,**** EXTRAS **** Tenant And Agent Verify All Info Please (29499408)',
       'Bedroom For Lease In A New Home In Popular North Area. Price Is $850, All Inclusive. Female Tenant Preferred. Tenant  Will Share The 3 Pc Bath, 2nd Floor Laundry, Kitchen & Common Areas (Which Will Be Furnished). Parking Spot Available For Each Tenant. Utilities Included.**** EXTRAS **** Located Close To Schools, Parks, 407, Shopping. Suitable For Professional, Mature Individual. (29433351)',
       "Great Location In The Heart Of North York, Great Schools, Minutes From Finch Subway And Highways. North York's Entertainment Centers. Spacious Kitchen. One Room On Main Floor Only. Kitchen, Living Room Share With Other Roommates. The Furnitures In The Pics Are All Included.**** EXTRAS **** Fridge, Cooktop & Fan Hood, Wash And Dry Machine. All Window Coverings & Electric Light Fixtures. (29444845)",
       'Basement Apartment In High Demand Area! Modern Laminate Flooring Throughout Whole Floor. 1 Driveway Parking Included. Steps To Bayview Secondary School W/I.B Program. Close To Catholic Public French School. Walking Distance To Public Transit, Shopping And All Amenities.**** EXTRAS **** All Elfs, Fridge, Stove, Washer, Dryer, Window Coverings, Cac. Tenant Pays Additional Utilities $150 Per Month (Hydro, Gas, Water & Hot Water Tank Rental). A++ Tenant Only! No Smoking/Pets. (29415311)',
       'Location, Location, Location, 1 Bedroom And Living Area(Can Be Converted To Second Bedroom) With Side Entrance Is Available For Lease From Jan 01/2022. Close To All Amenities Like Hwy 410, Transit, Plaza, Gas Station, Place Of Worship, School And More. 1 Parking Available .A+++ Tenant, Tenant Has To Pay 30% Utilities.**** EXTRAS **** Fridge And Stove, Shared Laundry, Tenant Has To Provide Liability Insurance Before Closing/ Completion. Old Mls Photos!! Separate Entrance To Basement! (29375399)',
       'Luxury, Bright And Spacious With Lots Of Windows. Renovated New Master Bedroom Appox.400 Sq Ft With Brand New 4-Pc Bath, Huge Walk In Closet With Shelves. Shared Kitchen Laundry. Walking Distance To Shops, Groceries, Tim Hortons, Trails, Parks, Markville Mall. Best Schools, Transportations. Car Parking Available, Utilities Included.**** EXTRAS **** Existing Shared Fridge, Stove, Dishwasher, Microwave, Washer & Dryer, Existing Light Fixture & Window Blinds. Cable Tv And Phone Excluded. (29543162)',
       "Great Property In Thornhill Neighborhood. Big Bachelor Basement Apartment With Pot Light, Freshly Painted, Separate Entrance, Partially Furnished, Easy Walk To Yonge, Transit, Schools, Shops And Has Big Back Yard. Tenant Will Pay1/3 Utilities. No Smoking & No Pet Is Preferred.**** EXTRAS **** Fridge, Cook Top, Microwave, Dryer & Washer, All Elf's. (29231283)",
       'High Demand Location, Cozy 1 Bdrm Apt. 1 Parking On Quiet Crescent, Min To Smart Center, Wal-Mart Prominent Mall, Aaa Tenant Prefers No Pet. ** This is a linked property.** **** EXTRAS **** Fridge, Stove, Elf. Share Laundry In Bsmt, 35% Heat & Hydro Split. (29614239)',
       'Location, Location! Beautiful Family Neighbourhood! 1 Bedroom Basement Apartment, Main Door Entrance! The Landlord Is Looking For A Small Family Or A Single Individual.**** EXTRAS **** Fridge, Stove, Shared Washer, Shared Dryer. (29564815)',
       'Fantastic 1 Bedroom Plus Living Room Basement In The Desirable Place Townhouse. Close To All Amenities, Schools, Transit, Shopping Center, Groceries, Banks, Hospitals And 401. Monthly Rent + 30% Of The Utilities. Nice Fit For Any Newly Wed Couple, Working Ladies Or A Small Family.**** EXTRAS **** One Parking Space Available On The Drive Way. Entrance From The Main Door. Space For Cooking And Heating Food Available. (29556563)',
       'Beautiful Renovated 1 Br Basement Apt, Laminate Flooring, 3 Pc Bathroom, Very Convenient Location, Walk To Yonge St, Close To Schools, Parks, Transit, Shopping And Highways. Rent Is Only For The Basement. Price Includes Utilities.**** EXTRAS **** Fridge, Stove, Microwave, Range Hood, Shared Washer & Dryer, 1 Parking Spot On Driveway Only. (29371132)',
       'Comfortable, Cozy And Clean Basement Unit In Sought After Streetsville.  Aaa Tenants Only, One Parking On Driveway And 1 Shed In Backyard For Additional Storage.**** EXTRAS **** All Appliances, Window Coverings And Light Fixtures To Remain On Property. (29592808)',
       'Located Close To Public Schools, High School, University, Centennial College, Scarborough Town Centre, Recreation Centre & Minutes To Hwy 401 And Bus Stand. Only Basement For Rent.**** EXTRAS **** Fridge, Stove, Washer & Dryer, All Elfs And Window Coverings. (29261062)',
       'All Inclusive 3 Bedroom And 1 Bathroom Basement With A Spacious Living/ Dining Room In A Quite Neighborhood In Markham. Great Space For A Couple/ Professionals! Walking Distance To Ttc/ Yrt, Pacific Mall, Go Train/Parks, Shopping, Groceries, Restaurants, Parks & More.**** EXTRAS **** Includes Fridge, Stove, Shared Washer, Hydro, Water, Heat, A/C, Internet, Cable Tv, 2 Car Parking (Tandem) (29168102)',
       'Location, Location, Location ...... Specious Bachelor Furnished Basement ..... Very Bright With 2 Windows And Separate Entrance From Garage. Including Hydro, Heat, Water, Separate (Dryer & Washer) & 1 Parking Spot. Steps To Bus Stops, Heart Land Shopping Place. 30 % Of Utility Bills (29607019)',
       'Bright And Specious W/O Basement Apartment Overlooking Into Open Space Backyard* , Separate Landry, Separate Side Entrance* No Pets, No Smoking Or Vaping Of Any Kind * Tenant Pay 1/3 Utility.Landlord Prefer A Couple.One Parking On Drive Way**** EXTRAS **** Fridge ,Stove,Washer Dryer,Microwave (29537301)',
       'Spacious 1 Br Unit In Vellore Village Community. High Ceilings, Laminate Flooring. Large Kitchen Is Equipped With S/S Appliances.  Laundry On-Site, One Car Parking Space On Private Drive Included. Steps To Transit, Schools, Shopping & All Amenities. Pay 1/3 Utility**** EXTRAS **** Fridge, Stove & Rangehood. Shared Laundry On Site. 1 Parking Space On Private Drive And 1/3 Utilities (Heat, Hydro, Water & Waste) No Pets & No Smoking Permitted. (29556592)',
       'New Renovations. Bright And Open! Located In A Family Friendly Neighbourhood, Lovingly Maintained Home Is Just Steps To Randall P.S And St. Francis Xaiver Catholic Elementary School, 5 Minute Drive To Milliken Mills H.S. Functional Layout, Main Floor Walks Out To Private Yard, 2nd Floor Primary Suite With Semi Ensuite Bath & His & Her Closets. Close To Grocery Stores, Pacific Mall, Restaurants, Parks, Ttc & Yrt Bus, 9 Minute Drive To Milliken Go Station. ** This is a linked property.** **** EXTRAS **** All Existing: Fridge, Stove, Washer, Dryer, Dishwasher, Central Air, All Light Fixtures, Tenant Pays Utilities. (29560603)',
       'New Renovations. Bright And Open! Located In A Family Friendly Neighbourhood, Lovingly Maintained Home Is Just Steps To Randall P.S And St. Francis Xaiver Catholic Elementary School, 5 Minute Drive To Milliken Mills H.S. Functional Layout, Main Floor Walks Out To Private Yard, 2nd Floor Primary Suite With Semi Ensuite Bath & His & Her Closets. Close To Grocery Stores, Pacific Mall, Restaurants, Parks, Ttc & Yrt Bus, 9 Minute Drive To Milliken Go Station. ** This is a linked property.** **** EXTRAS **** All Existing: Fridge, Stove, Washer, Dryer, Dishwasher, Central Air, All Light Fixtures, Tenant Pays Utilities. (29560603)',
       '. (29592813)',
       "Renovated Junior One Bedroom Apartment At This Highly Sought After Low-Rise On Huntley Street. Sunny East Facing Unit That's Perfect For Students And Young Professionals Seeking A Downtown Toronto Location. Steps To Sherbourne Subway Station And A Short Walk To Yorkville And Universities.**** EXTRAS **** Well Maintained Building With Updates Throughout. Parking Available For 150/Spot/Per Month. Rent Includes Utilities (Heat, Water And Hydro). Building Is Pet-Friendly. Card Operated Laundry Located In Building. Excellent Neighborhood. (29661556)",
       '2 Bedrooms Legal Apt( Basement) In Most Desirable Castlemore Area With Separate Entrance Open Concept Kitchen, Walk In To School, Transit, Shopping Close To Park, Goremeadow Recreation Centre & Library. 1 Parking Included And Minimum One Year Lease. Client Prefers Small Family Preferably. Working Professionals Welcome.**** EXTRAS **** Fridge, Stove, Washer & Dryer. Tenant Pay 30% Of Utilities. 1 Parking Included In The Price. Additional Parking Will Be Available At Extra $100/Month. (29532203)',
       "Spacious New Fully Renovated 1 Bedroom In Law Basement Furnished Apartment In The Detached Home In High Demand Location. Walking Distance To Yonge St & Mall And Shopping. Separate Entrance Very Clean And Modern.**** EXTRAS **** Utilities All Included In Rent, Separate Entrance, Fridges, Stoves, Micro Waive, Washer, Dryer, All Elf's. (29648743)",
       'Newly Renovated Unit At Excellent Central Location, Close To All Amenities. 1 Bedroom + 1 Den. Deck In Backyard, And Own Parking Space, Separate Entrance. Has Own Separate Hydro Meter.  This Unit Is A Must See! Tenant Pays Part Of Gas Calculated On Area Basis, Water Included In Rent. No Pets, No Smoking.**** EXTRAS **** Credit Check, Employment Letter, References, Tenant Insurance Required. (29372580)',
       '2 Bedrooms Legal Apt( Basement) In Most Desirable Castlemore Area With Separate Entrance Open Concept Kitchen, Walk In To School, Transit, Shopping Close To Park, Goremeadow Recreation Centre & Library. 1 Parking Included And Minimum One Year Lease. Client Prefers Small Family Preferably. Working Professionals Welcome.**** EXTRAS **** Fridge, Stove, Washer & Dryer. Tenant Pay 30% Of Utilities. 1 Parking Included In The Price. Additional Parking Will Be Available At Extra $100/Month. (29532203)',
       'New Renovated Bright & Spacious Two Bedroom Apartment In The Basement Level Of A Detached House Which Backs Onto Winbourne Park!Quiet Street. Separate Entrance. High Ceiling. All Rooms Have Above Grade Windows. New Laminate Floor, Separate Laundry, One Parking Spot. **Tenant Only Pays 30% Of The Utilities**.Close To Go Train, Bus Stops, Yonge St, 404 And All Your Shopping Needs.**** EXTRAS **** No Access To Garage & Backyard. **Price Is For 2 Bedroom Apt Only**.Stainless Steel Fridge & Stove, Washer & Dryer. Well Maintained Apartment. Must See! (29439472)',
       '1Bedroom With Walkup Basment In High Demand Area, Ensuite Laundry Steps To 24 Hours Ttc, Minutes To School, Shopping Center, Amazon Warehouse And Much More...**** EXTRAS **** Brand New Kitchen. Stove, Fridge And Spotlights (29563540)',
       'New 2 Bedroom Basement With Separate Entrance, Side Entrance, Separate Laundry, Big Windows For Plenty Of Natural Light, Full Washroom & Kitchen. 5 Min. Walk To Schools And Grocery Stores. Varioius Bus Stops In Walking Distance, One Parking Included. Pets And Smoke Free. Tenant To Pay 30% Of Utilities.**** EXTRAS **** Close To Public Transit, Schools,. Shopping, Parks, Recreation & All Other Amenties. (29442943)',
       "2 Br 1 Bath Basement Unit Conveniently Located At Taunton Rd And Garden St. 3 Mins Walk From Taunton Garden Plaza, Steps To Public Transit, Restaurants, Supermarket, Parks, Etc. Min To Hwy 412, 407 And 401. Separate Side Entrance Access To The Basement Unit. The Tenant Can Use Den Space Outside Of The Unit In The Common Space (Sharing With The Landlord's Son And His Dog Who Are Occasionally Occupying Another Room In The Basement).**** EXTRAS **** One Parking Spot On Driveway Included. White Fridge, Stove, B/I Range Hood. White Washer And Dryer. Tenant To Share 1/3 Of All Utility Costs (Cac, Heat, Hydro, Water, Gas). Existing Window Covering And All Elfs. (29390900)",
       '2 bedroom, 1 bathroom apartment located in a converted church in the quaint town of Durham with a well-equipped kitchen and just steps from downtown. Lovely community with plenty of beautiful scenery to enjoy including a large public park across the street, the Saugeen River, McGowan Falls, and picturesque trails. Parking includes 2 exclusive spaces and additional visitor parking. Covid 19 protocols in place. (64123198)',
       '2 Bedroom Bright & Spacious Basement Newly Renovated 1 Washrooms. Ceramic Flooring, Open Concept Kitchen And Living Room. Separate Entrance. No Smoking, No Pets. Excludes Cable And Phone. Prime Location In Pickering (Altona And Sheppard).  Close To All Amenities, School, Pickering Transit, Shopping Malls, Library, Banks  And 401.**** EXTRAS **** Fridge, Stove. Laundry (Separate). Utilities And 1 Parking Included. Complimentary Unlimited Internet. (29638481)',
       'Close To Clarkson Go Station, Next To A Park, Walking Distance To The Lake,  Spacious Basement W/Bedroom, Family/Living Room, Kitchen, Bathroom & Separate Entrance, Fresh Painting, Very Clean. All Are Included Except That The Tenant Will Pay 1/3 Electricity Bill.**** EXTRAS **** All Existing Fridge, Stove, Dish Washer, Washer And Dryer, Furnace, Central Air -- All Stay For Tenants To Use. (29387463)',
       'Absolutely Stunning And Welcoming Furnished Basement In A Great Milton Neighborhood. Very Bright! Renovated 2 Bdrm 1 Bath Apt W/Own Laundry! Open Concept Living Rm, Modern Kitchen, Tons Of Cabinets, Quartz Counter, Backsplash. No Grass Cutting! Tenant Is Responsible To Remove Snow On Walkway To The Bsmt & Own Driveway. Landlord Preference Is A Couple/International Students (Girls).**** EXTRAS **** One Of The Best And Most Prestigious Locally In Milton, Close To Hospital, Shopping, Restaurants, Daycare, Hwy 403 & 407. 1 Parking On Driveway (Left Side Of Garage). The Tenant Pays 30% Of Utilities. (29253172)',
       'Spacious & Bright Walkout Basement Apartment In A Backsplit Semi-Detached On A Quiet Street. Most Of The Areas Are Above Ground. Freshly Painted. Sun Filled Large Living Room Walking Out To Backyard. One Spacious Bedrooms With Large Windows. Large Kitchen With Combined Breakfast Area.  Close To Walking Trails, Hwy 401&407, Schools,Go Station, Toronto Premium Outlets, Heartland & Erin Mills Shopping Centres.**** EXTRAS **** Lower Level Only.  $1550 Plus 50% Of Utilities. All Existing Appliances, Elfs & Window Coverings. Lawn Mower And Snow Blower Are Provided By Landlord. (29597448)',
       'Absolutely Stunning And Welcoming Furnished Basement In A Great Milton Neighborhood. Very Bright! Renovated 2 Bdrm 1 Bath Apt W/Own Laundry! Open Concept Living Rm, Modern Kitchen, Tons Of Cabinets, Quartz Counter, Backsplash. No Grass Cutting! Tenant Is Responsible To Remove Snow On Walkway To The Bsmt & Own Driveway. Landlord Preference Is A Couple/International Students (Girls).**** EXTRAS **** One Of The Best And Most Prestigious Locally In Milton, Close To Hospital, Shopping, Restaurants, Daycare, Hwy 403 & 407. 1 Parking On Driveway (Left Side Of Garage). The Tenant Pays 30% Of Utilities. (29253172)'],
      dtype=object)

In [55]:
data[data['parking_space']>=2]

,Unnamed: 0,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
2,3,1,Location! Location! One Spacious Bedroom Avail...,bedroom,416,750,4.0,Single Family,1,0,Mississauga,Ontario L5W1V3,#BASEMEN -373 ARROWSMITH DR S
12,13,2,"All Upper Level 3 Br For Lease , Shared Kitche...",bedroom,647,800,2.0,Single Family,1,0,Toronto,Ontario M1B1R6,#ROOM -44 APPLEMORE RD
14,17,1,Bedroom For Lease In A New Home In Popular Nor...,bedroom,905,850,2.0,Single Family,1,0,Oshawa,Ontario L1L0M4,2556 CRAFTSMAN DR
24,29,1,"Great Location In The Heart Of North York, Gre...",bedroom,905,1000,2.0,Single Family,1,0,Toronto,Ontario M2N4R9,172 FINCH AVE
44,52,1,Basement Apartment In High Demand Area! Modern...,basement,905,1150,3.0,Single Family,1,0,Richmond Hill,Ontario L4C1B7,#BSMT -406 CENTRE ST E
70,82,1,"Location, Location, Location, 1 Bedroom And Li...",basement,905,1200,3.0,Single Family,1,1,Brampton,Ontario L6V4S1,#BSMT -41 CALM WATERS CRES
85,97,1,"Luxury, Bright And Spacious With Lots Of Windo...",apartment,416,1200,2.0,Single Family,4,0,Markham,Ontario L3S1G5,19 DEVONSHIRE AVE
98,111,1,Great Property In Thornhill Neighborhood. Big ...,basement,905,1250,5.0,Single Family,1,0,Markham,Ontario L3T1P7,70 GLEN CAMERON RD
113,132,1,"High Demand Location, Cozy 1 Bdrm Apt. 1 Parki...",basement,416,1280,2.0,Single Family,1,0,Vaughan,Ontario L4J4W7,#LOWER -89 GLEN CRES
122,143,4,"Location, Location! Beautiful Family Neighbour...",basement,416,1300,2.0,Single Family,3,0,Vaughan,Ontario L6A1Y7,17 CARRON AVE N
123,144,1,Fantastic 1 Bedroom Plus Living Room Basement ...,basement,905,1300,2.0,Single Family,1,1,Milton,Ontario L9T8H5,524 ATTENBOROUGH TERR N
127,150,1,"Beautiful Renovated 1 Br Basement Apt, Laminat...",basement,647,1300,2.0,Single Family,1,0,Richmond Hill,Ontario L4C4M2,54 ELGIN MILLS RD W
131,154,1,"Comfortable, Cozy And Clean Basement Unit In S...",basement,647,1300,5.0,Single Family,1,0,Mississauga,Ontario L5N1H5,#LOWER -20 ALPHA MILLS (LOWER) RD
150,176,1,"Located Close To Public Schools, High School, ...",basement,905,1300,4.0,Single Family,1,0,Toronto,Ontario M1G2L6,6 MID PINES RD
157,184,1,All Inclusive 3 Bedroom And 1 Bathroom Basemen...,basement,905,1300,2.0,Single Family,3,0,Markham,Ontario L3S1W3,#BSMT -152 CARTMEL DR
196,240,1,"Location, Location, Location ...... Specious B...",basement,855,1400,2.0,Single Family,1,0,Mississauga,Ontario L5V0C9,5426 BELLAGIO CRES
202,249,1,Bright And Specious W/O Basement Apartment Ove...,basement,905,1400,4.0,Single Family,1,0,Aurora,Ontario L4G6R4,#(BSMNT) -60 DAWLISH AVE
205,252,1,Spacious 1 Br Unit In Vellore Village Communit...,basement,905,1400,2.0,Single Family,1,0,Vaughan,Ontario,36 GENOA RD
209,256,1,New Renovations. Bright And Open! Located In A...,basement,905,1400,2.0,Single Family,2,0,Markham,Ontario L3S1J3,#BSMT -102 GALBRAITH CRES
246,301,1,New Renovations. Bright And Open! Located In A...,basement,905,1400,2.0,Single Family,2,0,Markham,Ontario L3S1J3,#BSMT -102 GALBRAITH CRES
253,309,1,. (29592813),NaN,905,1400,2.0,Single Family,1,0,Mississauga,Ontario L5M7N3,3537 BALA DR
281,342,1,Renovated Junior One Bedroom Apartment At This...,apartment,416,1450,150.0,Single Family,1,0,Toronto,Ontario M4Y2L1,#102 -44 HUNTLEY ST
287,348,1,2 Bedrooms Legal Apt( Basement) In Most Desira...,basement,866,1450,2.0,Single Family,2,0,Brampton,Ontario L6P3G4,#BSMT -44 SUMMERSHADE ST
297,358,1,Spacious New Fully Renovated 1 Bedroom In Law ...,basement,905,1450,6.0,Single Family,1,0,Richmond Hill,Ontario L4C8G4,14 DUNBARTON CRT
302,363,1,Newly Renovated Unit At Excellent Central Loca...,basement,416,1450,4.0,Single Family,1,0,Oshawa,Ontario L1H5K6,U B 555 RITSON RD S
303,364,1,2 Bedrooms Legal Apt( Basement) In Most Desira...,basement,866,1450,2.0,Single Family,2,0,Brampton,Ontario L6P3G4,#BSMT -44 SUMMERSHADE ST
327,399,4,New Renovated Bright & Spacious Two Bedroom Ap...,basement,416,1499,4.0,Single Family,3,2,Richmond Hill,Ontario L4C9Z8,#BSMT -37 JUSTUS DR
329,401,1,1Bedroom With Walkup Basment In High Demand Ar...,basement,416,1499,2.0,Single Family,1,0,Toronto,Ontario M1X2B1,26 QUIETBROOK CRES
333,408,1,"New 2 Bedroom Basement With Separate Entrance,...",basement,647,1500,4.0,Single Family,2,0,Milton,Ontario L9T6T2,1074 MC CUAIG DR
362,443,1,2 Br 1 Bath Basement Unit Conveniently Located...,basement,905,1500,4.0,Single Family,2,0,Whitby,Ontario L1R2C6,34 CLUNE PL
381,467,1,"2 bedroom, 1 bathroom apartment located in a c...",apartment,647,1500,2.0,Single Family,2,0,Durham,Ontario N0G1R0,108 QUEEN Street N
385,471,1,2 Bedroom Bright & Spacious Basement Newly Ren...,basement,416,1500,4.0,Single Family,2,0,Pickering,Ontario L1V6N3,281 WATERFORD GATE
438,530,1,"Close To Clarkson Go Station, Next To A Park, ...",basement,905,1550,4.0,Single Family,1,0,Mississauga,Ontario L5J4L6,#BSMT -1078 KOS BLVD
439,531,1,Absolutely Stunning And Welcoming Furnished Ba...,basement,647,1550,3.0,Single Family,2,0,Milton,Ontario L9T5L9,1583 RAMSHAW CRES
442,542,1,Spacious & Bright Walkout Basement Apartment I...,basement,416,1550,3.0,Single Family,1,0,Mississauga,Ontario L5N2G2,#-LOWER -2501 COBBINSHAW CIRC
451,553,1,Absolutely Stunning And Welcoming Furnished Ba...,basement,647,1550,3.0,Single Family,2,0,Milton,Ontario L9T5L9,1583 RAMSHAW CRES

In [54]:
data.iloc[2,6] = 0
data.iloc[12,6] = 1
data.iloc[14,6] = 1
data.iloc[44,6] = 1
data.iloc[70,6] = 1
data.iloc[98,6] = 1
data.iloc[123,6] = 1
data.iloc[131,6] = 1
data.iloc[44,6] = 1

4.0

In [ ]:
data.iloc[381,6] = 2

In [ ]:
data.iloc[85,3] = 'apartment'

In [50]:
data.iloc[381,6]

2.0

# Drop cities with 1 data

In [5]:
data = pd.read_csv('./GTA_pandas.csv')

In [48]:
data[(data['city'] == 'Markham') & (data['room type'] == 'bedroom')]

,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
7,2,Fully Furnished 1 Bedroom For Rent. Well Maint...,bedroom,416,800,1.0,Single Family,1,0,Markham,Ontario L6B0J3,#(1BR) -11 SUMMERSIDE ST

In [10]:
data.drop(['Unnamed: 0'], axis = 1, inplace=True)

In [11]:
data.drop(['Unnamed: 0.1'], axis = 1, inplace=True)

In [40]:
data['city'].value_counts()

Toronto          214
Brampton          49
Mississauga       39
Markham           34
Richmond Hill     26
Oshawa            23
Vaughan           20
Ajax              11
Milton            10
Aurora             9
Pickering          7
Newmarket          4
Whitby             3
Name: city, dtype: int64

In [32]:
data[(data['city'] == 'Durham') | (data['city']=='Uxbridge') | (data['city']=='Georgina')| (data['city']=='Clarington')]

,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
190,1,Great Condition 1-Bedroom Apartment In The Hea...,bedroom,905,1380,0.0,Single Family,1,0,Uxbridge,Ontario L9P1P3,#4 -2 BASCOM ST S
221,1,"Newly Renovated, Open Concept, Legal Basement ...",basement,905,1400,1.0,Single Family,1,0,Clarington,Ontario L1C4R8,95B CONCESSION - LOWER RD E
381,1,"2 bedroom, 1 bathroom apartment located in a c...",apartment,647,1500,2.0,Single Family,2,0,Durham,Ontario N0G1R0,108 QUEEN Street N
391,1,All Inclusive Brand New Basement Apartment Wit...,basement,905,1500,1.0,Single Family,1,0,Georgina,Ontario L4P3X7,52 FAIRWOOD DR

In [39]:
data = data.drop(190)
data = data.drop(221)
data = data.drop(381)
data = data.drop(391)

In [43]:
data[data['room type'].isnull()]

,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
253,1,. (29592813),NaN,905,1400,2.0,Single Family,1,0,Mississauga,Ontario L5M7N3,3537 BALA DR
312,1,. (29657975),NaN,877,1490,1.0,Single Family,2,0,Vaughan,Ontario L4J8S5,34 MAPLE SUGAR LANE

In [44]:
data = data.drop(253)
data = data.drop(312)

In [45]:
data.to_csv('./final_gta.csv')

# replace na, drop duplicates

In [110]:
data['parking_space'].fillna(0, inplace=True)

In [112]:
data.drop_duplicates()

,Address,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom
0,"689 DOON VILLAGE Road Unit# 304-3|Kitchener, O...",2,STUDENT BEDROOM RENTAL in MALE-ONLY UNIT. $495...,bedroom,416,$495/Monthly,0.0,Single Family,4,0
1,"#1109 -2910 HIGHWAY 7 RD|Vaughan, Ontario L4K0H8",1,Solarium Room For Rent* Solarium Has A Window ...,bedroom,905,$700/Monthly,0.0,Single Family,1,0
2,"##3 -105 BROCK ST S|Whitby, Ontario L1N4J9",1,Fabulous Upper Floor 1 Bedroom Is Available Fo...,bedroom,905,$750/Monthly,0.0,Single Family,1,0
3,"#BASEMEN -373 ARROWSMITH DR S|Mississauga, On...",1,Location! Location! One Spacious Bedroom Avail...,bedroom,416,$750/Monthly,4.0,Single Family,1,0
4,"#UPPER -31B SOUTH STATION ST|Toronto, Ontario ...",1,Located Close To Go Station At Weston And Lawr...,upper-unit,905,$750/Monthly,1.0,Single Family,1,0
...,...,...,...,...,...,...,...,...,...,...
545,"#LOWER -509 ADELAIDE AVE W|Oshawa, Ontario L1J2S2",1,2 Bedroom Basement Apartment. Private Entrance...,basement,905,"$1,550/Monthly",0.0,Single Family,2,0
548,"36 LAUDERDALE DR|Vaughan, Ontario L6A4G8",1,"Never Lived In, Brand New, Bsmnt Apartment. Br...",basement,416,"$1,550/Monthly",1.0,Single Family,2,0
549,"26 ALICE CRES|Toronto, Ontario M1R4N7",1,Basement Only. Must See Upgraded Basement In O...,basement,647,"$1,550/Monthly",0.0,Single Family,2,0
550,"#514 -170 BAYVIEW AVE|Toronto, Ontario M5A0G1",1,Contemporary Open Concept Bachelor Suite W/ Lo...,apartment,905,"$1,550/Monthly",0.0,Single Family,0,0
554,"220 RAVENSCROFT RD|Ajax, Ontario L1T2T3",1,2 Bedroom Basement Apartment In Hear Of Ajax. ...,basement,416,"$1,550/Monthly",0.0,Single Family,2,0

# Separate Address into address, city, province

In [120]:
#Address
data['Address'][0].partition('|')[0]

'689 DOON VILLAGE Road Unit# 304-3'

In [124]:
#city
data['Address'][0].partition('|')[2].partition(',')[0]

'Kitchener'

In [125]:
#province
data['Address'][0].partition('|')[2].partition(',')[2]

' Ontario N2P1A1'

In [175]:
data['address'] = data['Address'].apply(lambda x: x.partition('|')[0])
data['city'] = data['Address'].apply(lambda x: x.partition('|')[2].partition(',')[0])
data['province'] = data['Address'].apply(lambda x: x.partition('|')[2].partition(',')[2])

In [178]:
data.drop('Address', axis=1, inplace=True)

# Get only digits for the Price

In [162]:
data['price'][0].partition('/')[0][1:]

'495'

In [163]:
data['price'] = data['price'].apply(lambda x: x.partition('/')[0][1:])

In [166]:
data['price'][0].replace(',', '')

'495'

In [169]:
data['price'] = data['price'].str.replace(',', '')

In [198]:
data

,bathrooms,public_remarks,room type,areacode,price,parking_space,property_type,bedroom,spareroom,city,province,address
0,2,STUDENT BEDROOM RENTAL in MALE-ONLY UNIT. $495...,bedroom,416,495,0.0,Single Family,0,0,Kitchener,Ontario N2P1A1,689 DOON VILLAGE Road Unit# 304-3
1,1,Solarium Room For Rent* Solarium Has A Window ...,bedroom,905,700,0.0,Single Family,1,0,Vaughan,Ontario L4K0H8,#1109 -2910 HIGHWAY 7 RD
2,1,Fabulous Upper Floor 1 Bedroom Is Available Fo...,bedroom,905,750,0.0,Single Family,1,0,Whitby,Ontario L1N4J9,##3 -105 BROCK ST S
3,1,Location! Location! One Spacious Bedroom Avail...,bedroom,416,750,4.0,Single Family,1,0,Mississauga,Ontario L5W1V3,#BASEMEN -373 ARROWSMITH DR S
4,1,Located Close To Go Station At Weston And Lawr...,upper-unit,905,750,1.0,Single Family,1,0,Toronto,Ontario M9N2B2,#UPPER -31B SOUTH STATION ST
...,...,...,...,...,...,...,...,...,...,...,...,...
550,1,Contemporary Open Concept Bachelor Suite W/ Lo...,apartment,905,1550,0.0,Single Family,0,0,Toronto,Ontario M5A0G1,#514 -170 BAYVIEW AVE
551,1,"Welcome To A Bright, Freshly Painted, Lower Le...",basement,905,1550,0.0,Single Family,1,0,Brampton,Ontario L6V3N5,#LOWER -54 CARTER DR
552,1,Legal Bsmt 2 Bedroom Apartment For Rent. Newer...,basement,905,1550,1.0,Single Family,2,0,Brampton,Ontario L7A1L6,48 COLLINGWOOD AVE
553,1,Absolutely Stunning And Welcoming Furnished Ba...,basement,647,1550,3.0,Single Family,2,0,Milton,Ontario L9T5L9,1583 RAMSHAW CRES
554,1,2 Bedroom Basement Apartment In Hear Of Ajax. ...,basement,416,1550,0.0,Single Family,2,0,Ajax,Ontario L1T2T3,220 RAVENSCROFT RD

# Correct Datatype

In [205]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bathrooms       555 non-null    int64
 1   public_remarks  555 non-null    object
 2   room type       553 non-null    object
 3   areacode        555 non-null    int64
 4   price           555 non-null    int64
 5   parking_space   555 non-null    float64
 6   property_type   555 non-null    object
 7   bedroom         555 non-null    int64
 8   spareroom       555 non-null    int64
 9   city            555 non-null    object
 10  province        555 non-null    object
 11  address         555 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 52.2+ KB

In [204]:
data['bathrooms'] = pd.to_numeric(data['bathrooms'])
data['price'] = pd.to_numeric(data['price'])
data['parking_space'] = pd.to_numeric(data['parking_space'])
data['spareroom'] = pd.to_numeric(data['spareroom'])
data['bedroom'] = pd.to_numeric(data['bedroom'])

# Explore..!

In [243]:
data['city'].value_counts()

Toronto                      214
Brampton                      49
Mississauga                   39
Markham                       34
Richmond Hill                 26
Brantford                     25
Oshawa                        23
Hamilton                      21
Vaughan                       20
Ajax                          11
Niagara Falls                 11
Milton                        10
Aurora                         9
Pickering                      7
                               7
Barrie                         6
St. Catharines                 5
Newmarket                      4
Whitby                         3
Kitchener                      3
Waterloo                       2
Wasaga Beach                   2
Cambridge                      2
Shelburne                      2
Whitchurch-Stouffville         2
Southgate                      2
Stirling                       1
Durham                         1
Clarington                     1
Peterborough                   1
Dundalk                        1
Waterdown                      1
Allanburg                      1
Quinte West                    1
Niagara-on-the-Lake            1
Collingwood                    1
Uxbridge                       1
Bradford West Gwillimbury      1
Oakville                       1
Thorold                        1
Millbrook Village              1
Georgina                       1
Name: city, dtype: int64

In [244]:
gta = data[data['city'].isin(['Whitby', 'Markham', 'Mississauga', 'Oshawa', 'Richmond Hill', 'Newmarket', 'Vaughan', 'Aurora', 'Toronto', 'Uxbridge', 'Pickering', 'Clarington', 'Milton', 'Brampton', 'Ajax', 'Durham', 'Georgina'])]

In [245]:
gta['city'].value_counts()

Toronto          214
Brampton          49
Mississauga       39
Markham           34
Richmond Hill     26
Oshawa            23
Vaughan           20
Ajax              11
Milton            10
Aurora             9
Pickering          7
Newmarket          4
Whitby             3
Uxbridge           1
Clarington         1
Georgina           1
Durham             1
Name: city, dtype: int64

In [246]:
gta.groupby('city')['price'].describe()

,count,mean,std,min,25%,50%,75%,max
city,,,,,,,,
Ajax,11.0,1468.181818,78.334945,1350.0,1400.0,1500.0,1525.0,1550.0
Aurora,9.0,1361.111111,157.674066,1100.0,1200.0,1400.0,1500.0,1550.0
Brampton,49.0,1409.612245,145.909620,899.0,1400.0,1450.0,1500.0,1550.0
Clarington,1.0,1400.000000,NaN,1400.0,1400.0,1400.0,1400.0,1400.0
Durham,1.0,1500.000000,NaN,1500.0,1500.0,1500.0,1500.0,1500.0
Georgina,1.0,1500.000000,NaN,1500.0,1500.0,1500.0,1500.0,1500.0
Markham,34.0,1305.676471,180.389431,800.0,1200.0,1372.5,1445.0,1500.0
Milton,10.0,1435.000000,108.140855,1300.0,1312.5,1500.0,1500.0,1550.0
Mississauga,39.0,1344.230769,196.805202,750.0,1250.0,1400.0,1500.0,1550.0
Newmarket,4.0,1237.500000,217.466473,950.0,1137.5,1275.0,1375.0,1450.0
Oshawa,23.0,1314.869565,188.347190,800.0,1249.5,1350.0,1450.0,1550.0
Pickering,7.0,1357.142857,207.019668,900.0,1400.0,1400.0,1450.0,1500.0
Richmond Hill,26.0,1310.038462,147.297109,999.0,1200.0,1325.0,1400.0,1550.0
Toronto,214.0,1355.948598,177.599201,750.0,1299.0,1400.0,1500.0,1550.0
Uxbridge,1.0,1380.000000,NaN,1380.0,1380.0,1380.0,1380.0,1380.0
Vaughan,20.0,1313.250000,249.421831,700.0,1200.0,1387.5,1500.0,1550.0
Whitby,3.0,1183.000000,388.222874,750.0,1024.5,1299.0,1399.5,1500.0

In [262]:
#sd
gta.groupby('city')['price'].describe().iloc[:,2]

city
Ajax              78.334945
Aurora           157.674066
Brampton         145.909620
Clarington              NaN
Durham                  NaN
Georgina                NaN
Markham          180.389431
Milton           108.140855
Mississauga      196.805202
Newmarket        217.466473
Oshawa           188.347190
Pickering        207.019668
Richmond Hill    147.297109
Toronto          177.599201
Uxbridge                NaN
Vaughan          249.421831
Whitby           388.222874
Name: std, dtype: float64

In [261]:
#50 percentile
gta.groupby('city')['price'].describe().iloc[:,5]

city
Ajax             1500.0
Aurora           1400.0
Brampton         1450.0
Clarington       1400.0
Durham           1500.0
Georgina         1500.0
Markham          1372.5
Milton           1500.0
Mississauga      1400.0
Newmarket        1275.0
Oshawa           1350.0
Pickering        1400.0
Richmond Hill    1325.0
Toronto          1400.0
Uxbridge         1380.0
Vaughan          1387.5
Whitby           1299.0
Name: 50%, dtype: float64

In [257]:
#min
gta.groupby('city')['price'].min().sort_values()

city
Vaughan           700
Mississauga       750
Toronto           750
Whitby            750
Markham           800
Oshawa            800
Brampton          899
Pickering         900
Newmarket         950
Richmond Hill     999
Aurora           1100
Milton           1300
Ajax             1350
Uxbridge         1380
Clarington       1400
Durham           1500
Georgina         1500
Name: price, dtype: int64

In [258]:
gta.groupby('city')['price'].max().sort_values()

city
Uxbridge         1380
Clarington       1400
Newmarket        1450
Whitby           1500
Durham           1500
Georgina         1500
Markham          1500
Pickering        1500
Toronto          1550
Richmond Hill    1550
Ajax             1550
Vaughan          1550
Milton           1550
Brampton         1550
Aurora           1550
Oshawa           1550
Mississauga      1550
Name: price, dtype: int64

In [271]:
gta.groupby('city')['price'].mean().sort_values()

city
Whitby           1183.000000
Newmarket        1237.500000
Markham          1305.676471
Richmond Hill    1310.038462
Vaughan          1313.250000
Oshawa           1314.869565
Mississauga      1344.230769
Toronto          1355.948598
Pickering        1357.142857
Aurora           1361.111111
Uxbridge         1380.000000
Clarington       1400.000000
Brampton         1409.612245
Milton           1435.000000
Ajax             1468.181818
Durham           1500.000000
Georgina         1500.000000
Name: price, dtype: float64

In [248]:
gta['room type'].value_counts()

basement      370
bedroom        48
apartment      26
upper-unit      7
Name: room type, dtype: int64

In [256]:
gta.groupby('city')['room type'].value_counts()

city           room type
Ajax           basement       11
Aurora         basement        8
               bedroom         1
Brampton       basement       46
               apartment       2
               upper-unit      1
Clarington     basement        1
Durham         apartment       1
Georgina       basement        1
Markham        basement       32
               bedroom         2
Milton         basement       10
Mississauga    basement       35
               bedroom         3
Newmarket      basement        3
               apartment       1
Oshawa         basement       11
               bedroom         6
               apartment       4
               upper-unit      2
Pickering      basement        7
Richmond Hill  basement       26
Toronto        basement      162
               bedroom        31
               apartment      17
               upper-unit      4
Uxbridge       bedroom         1
Vaughan        basement       15
               bedroom         3
               apartment       1
Whitby         basement        2
               bedroom         1
Name: room type, dtype: int64

In [249]:
gta.groupby('room type')['price'].describe()

,count,mean,std,min,25%,50%,75%,max
room type,,,,,,,,
apartment,26.0,1405.769231,152.733050,950.0,1381.25,1450.0,1495.0,1550.0
basement,370.0,1377.783784,147.759736,750.0,1300.00,1400.0,1500.0,1550.0
bedroom,48.0,1165.395833,265.260750,700.0,893.75,1200.0,1400.0,1550.0
upper-unit,7.0,1142.857143,238.796586,750.0,1050.00,1200.0,1250.0,1450.0

In [250]:
gta.groupby('room type')['price'].mean().sort_values(ascending=True)

room type
upper-unit    1142.857143
bedroom       1165.395833
basement      1377.783784
apartment     1405.769231
Name: price, dtype: float64

In [251]:
gta.groupby('room type')['spareroom'].value_counts()

room type   spareroom
apartment   0             26
basement    0            338
            1             31
            2              1
bedroom     0             48
upper-unit  0              7
Name: spareroom, dtype: int64

In [252]:
gta.to_csv('./GTA_pandas.csv')

# Insert into DB

In [158]:
engine = sqlalchemy.create_engine('postgresql://ebeen94:qwer1234!@localhost:5432/portfolio')

In [159]:
data.to_sql('GTA', engine)